spring:
    application:
        name: analytics-service
    main:
        banner-mode: console
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

management:
    endpoints:
        web:
            exposure:
                include: health, info

    tracing:
        sampling:
            probability: 1.0

    endpoint:
        health:
            show-details: never

logging:
    level:
        root: INFO
