server:
    port: ${ANALYTICS_SERVICE_DEV_PORT}

spring:
    config:
        activate:
            on-profile: dev

    devtools:
        add-properties: true

    web:
        error:
            include-message: always
            include-stacktrace: always

    # datasource:
    #     url: ${DEV_POSTGRES_URL}
    #     username: ${DEV_POSTGRES_USERNAME}
    #     password: ${DEV_POSTGRES_PASSWORD}

    # jpa:
    #     hibernate:
    #         ddl-auto: validate
    #     show-sql: true

    #     properties:
    #         hibernate:
    #             format_sql: true

    springdoc:
        api-docs:
            path: /v3/api-docs
            enabled: true

        swagger-ui:
            enabled: true

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

openapi:
    service:
        api-docs: v3/api-docs
        title: Analytics Service API
        description: API documentation for Analytics Service
        version: 1.0.0
        server: ${OPENAPI_SERVER_URL:http://localhost:${server.port}}
