spring:
  main:
    banner-mode: console

  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
