server:
    port: ${AUTH_SERVICE_DEV_PORT}

spring:
    config:
        activate:
            on-profile: dev

    devtools:
        add-properties: true

    web:
        error:
            include-message: always
            include-stacktrace: always

    datasource:
        url: ${DEV_POSTGRES_URL}
        username: ${DEV_POSTGRES_USERNAME}
        password: ${DEV_POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

        properties:
            hibernate:
                format_sql: true

    jwt:
        secretKey: ${JWT_SECRET_KEY}

    springdoc:
        api-docs:
            path: /v3/api-docs
            enabled: true

        swagger-ui:
            enabled: true

openapi:
    service:
        api-docs: v3/api-docs
        title: Auth Service API
        description: API documentation for Auth Service
        version: 1.0.0
        server: ${OPENAPI_SERVER_URL:http://localhost:${server.port}}
